spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simple_functions?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: 110110110
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 6000ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 6000ms
