spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simple_functions?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: 110110110
